language: java
jdk:
  - oraclejdk8
services:
  - postgresql
postgres:
  adapter: postgresql
  username: postgres
  password: admin
before_script:
  - "psql -U postgres template1 -c \"alter user postgres with password 'admin'\""
notifications:
  slack: dreamteamsi1:3Ngf9fFmx8JOmxaA7GDwOdd6
